Report dialog
spacemeshos/smapp pull request #1032
Opened 2022-11-30 22:13 UTC by maparr

2022-12-19 21:08 UTC, brusherru requested changes
1. ❗️Had some errors with installing dependencies (peer dependencies were not installed? 🤔 ). Fixed by adding `@sentry/minimal` and @sentry/types` into dependencies. Can you check this out (pls ensure that you haven't it installed globally)?

2. ❗️Got an exception trying to send the report.
     ![image](https://user-images.githubusercontent.com/1897530/208517916-8fe7cdfb-a430-4384-8d3d-e93087cdb2ab.png)
     It does not import `Severity` well as for the default log level (`Severity.Info`), due to the deprecation. So choose and add the proper version. Probably it is the consequence of the issue mentioned first. I also proposed kludges that worked for me after installing these two libs. But I believe they should be resolved as peer dependencies, meanwhile I've not succeeded with it quickly 🤔 

3. After sending the report and opening the "Report issue" modal again I see the previous content. Let's reset the description field to the placeholder template on success, but keep the name and email. (sounds like that will be useful to store them between app sessions, but not sure that it is a good idea to store it decrypted in settings.json. So out of scope for sure)

4. Let's notify User about success submission somehow. I see a couple of easy ways:
     1. Do not hide the report modal dialog box, but change content to something like "Thanks for the report! Spacemesh team will investigate it and open an issue on Github. They may ask you to provide some details via email you have specified." and put the button "Report new issue", which will get the User back
     2. Hide the report modal and show another tiny one, saying the same and just the "Close" button.

In the rest, seems good.

2022-12-19 21:08 UTC, brusherru commented on app/components/common/Feedback.tsx
> +`;
```suggestion

### Expected behavior

What should happen?

### Actual behavior

What’s happening now?
`;
```

2022-12-19 21:08 UTC, brusherru commented on app/sentry.ts
> +import * as Sentry from '@sentry/react';
See the second point in the main comment

```suggestion
import * as Sentry from '@sentry/react';
import { Severity } from '@sentry/types';
```

2022-12-19 21:08 UTC, brusherru commented on app/sentry.ts
> +  return Sentry.captureMessage(message);
See the second point in the main comment.

```suggestion
  return Sentry.captureMessage(message, 'info' as Severity);
```

2022-12-21 02:41 UTC, maparr commented
Hi @brusherru ,
1. the node_moduels issues also happened with me, after new develop branch updates , just a clean reinstall should fix it 

2. small modal was added.

3. reset fields implemented also

2022-12-21 20:45 UTC, monikasmolarek commented
Checked on Mac and Win. Everything works as expected (Smapp -> Sentry. Maybe Slack notifications to be reviewed in the future). Very nice, user-friendly layout and messages.

2022-12-24 02:18 UTC, brusherru approved these changes
👍

2022-12-26 19:55 UTC, merged