Feature: handle PoS status
spacemeshos/smapp pull request #1047
Opened 2022-12-15 14:35 UTC by maparr

2022-12-20 02:54 UTC, brusherru requested changes
The rest seems OK, but still can't test it entirely.
Having some problems with syncing the latest node 🤔

2022-12-20 02:54 UTC, brusherru commented on proto/spacemesh/v1/PostSetupStatus.ts
> +  STATE_NOT_STARTED = 1, // resume . (I stooped I can resume  |> there is no PoS data, u have to wait) or node is not init PoST
Beware of upgrading .ts implementations manually.

The proper way is to update .proto files (if you don't like to copy files — we can replace it as a submodule, then you'll need only to bump the version in the file & re-generate proto files.

So, update the proto files to the ones used by go-spacemesh (v1.5.3). And run `yarn build:proto`

2022-12-20 02:54 UTC, brusherru commented on desktop/NodeManager.ts
> +      this.nodeProcess.kill('SIGKILL');
Wait. It should not be so rough.
Send `SIGTERM` instead.

```suggestion
      this.nodeProcess.kill('SIGTERM');
```

2022-12-21 12:47 UTC, maparr commented on proto/spacemesh/v1/PostSetupStatus.ts
> +  STATE_NOT_STARTED = 1, // resume . (I stooped I can resume  |> there is no PoS data, u have to wait) or node is not init PoST
@brusherru , yes, for sure, waiting for the Proto files update, go-spacemesh release, and network.

2022-12-21 18:48 UTC, brusherru commented on proto/spacemesh/v1/PostSetupStatus.ts
> +  STATE_NOT_STARTED = 1, // resume . (I stooped I can resume  |> there is no PoS data, u have to wait) or node is not init PoST
Proto files are already there: https://github.com/spacemeshos/api/blob/51db8aeb7ef5bad8f00a9e304a75b004bf0a5978/spacemesh/v1/smesher_types.proto#L120-L132. You just need to copy-paste the entire file and build ts-files :)

2022-12-24 01:58 UTC, brusherru approved these changes
👍

2022-12-24 02:06 UTC, brusherru requested changes
Wait-wait :)

Probably it is a draft and that's why you made a couple of strange commits :)
I mean this https://github.com/spacemeshos/smapp/pull/1047/files#diff-a67f63211f160c9d04983b5160ea7a39d5e30acceeea8bbef04106eabdbfe172R58-R62 and what is the purpose of https://github.com/spacemeshos/smapp/pull/1047/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R23 ?

I believe there should be no [skip ci] commits in the branch that is going to be merged

2022-12-24 02:09 UTC, maparr commented
@brusherru , the second one about Windows OS, is a way how to avoid the issue with go version check verification with custom build on the Windows, will be documented in our wiki pages

and first, will be removed, I'm checking rewards on network 997 and checking details. The comment will be removed, just testing is an issue will be with it or not

2022-12-26 19:56 UTC, maparr commented
Working with 997 netowrk

2022-12-26 19:57 UTC, maparr commented
Hi @monikasmolarek , can u check this solution on Windows and MacOS, go-spacemesh commit 45e5b646f83c3f5a54d13091bd9306f146cd9ede and network 997

2022-12-26 23:40 UTC, brusherru approved these changes
👍

2022-12-28 16:23 UTC, monikasmolarek commented
Works as expected on Windows and Mac. Creating, editing, deleting PoS all correct, rewards also correctly received, although shown in Transactions log only after restarting Smapp.

2022-12-29 14:30 UTC, merged