Fix saving transaction notes
spacemeshos/smapp pull request #1056
Opened 2022-12-22 04:33 UTC by brusherru

It fixes #1050 

PR based on top of Max's branch to make the testing process less painful.
It can be merged into develop without any conflicts.

2022-12-23 15:58 UTC, monikasmolarek reviewed
Notes are saved correctly and remain in the log after changing the screen and logging out&in.  However, the Smapp reinstallation (even to the same version)-keeps the Transactions log correctly but wipes out all the notes from the history.

2022-12-24 12:13 UTC, monikasmolarek commented
Deleting Wallet to be corrected. Checked only on Mac as for now. 

Issue: while having more than one Wallet created and stored in the App files/directory, the "Delete" button deletes the first Wallet (in chronological order - the first created), not the currently opened Wallet that was supposed to be deleted. 


https://user-images.githubusercontent.com/89876259/209435793-dd92aa47-5e6f-4945-8256-034abd291d13.mov

2022-12-24 13:37 UTC, monikasmolarek requested changes
I also checked on Win, and the same behavior for deleting the Wallets - no matter which Wallet is currently opened and supposed to be deleted, the "Delete" button in settings removes other Wallets- starting from the oldest one.

2022-12-27 00:12 UTC, brusherru commented
@monikasmolarek Thanks!
Now it fixed :)

2022-12-28 00:53 UTC, monikasmolarek requested changes
Delete Wallets OK on Mac and Win
Transaction Notes OK on Mac and Win
Wipe Out OK on Mac
Wipe out on Win not enough:
![2022-12-28_01h45_10](https://user-images.githubusercontent.com/89876259/209741059-c6857276-1168-4092-a01c-14803a2553ba.gif)

2022-12-29 20:32 UTC, brusherru commented
@monikasmolarek now wipe out should work.
On Windows, it may leave some electron-related data there that does not contain sensitive data (wallets/logs/etc).

2022-12-29 21:53 UTC, monikasmolarek approved these changes
Checked on Win and Mac: 
- deleting wallets OK,
- wipe out data OK on both
didn't check transaction notes this time

2022-12-30 01:21 UTC, merged