fix: Archiving logs loses big amount of data
spacemeshos/smapp pull request #1106
Opened 2023-01-27 18:42 UTC by maparr

Try to close #1080 
<img width="977" alt="Screenshot 2023-01-27 at 13 42 25" src="https://user-images.githubusercontent.com/54288612/215168750-fea655a1-1635-4163-8d63-2ca792b26c16.png">

2023-01-27 18:43 UTC, maparr commented
Hi @monikasmolarek , when u will have time may u check

2023-01-28 00:50 UTC, brusherru commented
@maparr `logrotator` lib is using `copytruncate` under the hood
Just replace it with https://www.npmjs.com/package/logrotate-stream and pipe stdout&stderr right there.
I believe it should work :)

2023-01-28 02:45 UTC, maparr commented
@brusherru checked this lib, a problem with rotation, if rotation files exceeded the max level, logs won't be rotated and will be streamed to the file with no restriction. Need to find another lib or fork it 
<img width="672" alt="Screenshot 2023-01-27 at 21 43 09" src="https://user-images.githubusercontent.com/54288612/215238070-78b1174f-ce8c-4aa2-9bba-f8db7ecc1ed6.png">

2023-01-28 03:26 UTC, maparr commented
works fine, with 5k size rotation 
<img width="773" alt="Screenshot 2023-01-27 at 22 18 30" src="https://user-images.githubusercontent.com/54288612/215239473-9f52ef2d-3ae4-468e-8b30-b040fd634eb6.png">

2023-01-28 03:55 UTC, brusherru requested changes
1. Do not move `fonts.d.ts` and `images.d.ts` to the "global" scope. It is related only to GUI — so let's keep it there.
2. Don't repeat the code ;)

2023-01-28 03:55 UTC, brusherru commented on types/logrotate-stream.d.ts
> +// Type definitions for logrotate-stream 0.2.5
Why it is here instead of package.json `yarn add -D @types/logrotate-stream`? :)

2023-01-30 22:08 UTC, monikasmolarek commented
Tested on Windows and worked pretty well; however, on Mac, the file that reached already 104Mb didn’t get archived. Continued to be used/updated. I will re-test it cause I fumbled a bit in the log file to speed up the whole process, so it might be my fault.

2023-01-31 17:32 UTC, monikasmolarek approved these changes
looks ok :) if no issues with smapp, network etc. it works fine.

2023-01-31 17:32 UTC, monikasmolarek commented on desktop/NodeManager.ts
> +      keep: 5,
I trust it will be enough, the decision is yours Guys :)

2023-02-02 20:29 UTC, brusherru approved these changes

2023-02-02 20:39 UTC, merged