chore: upgrade sentry
spacemeshos/smapp pull request #1109
Opened 2023-01-27 21:29 UTC by maparr

2023-01-27 21:41 UTC, maparr commented
when will be finished migration to the latest yarn #1108 , we can replace it with a yarn patch. Currently, we have an issue with yarn.lock and old packages. Story with a summary of what to update and where in progress.

2023-01-31 03:44 UTC, maparr commented
Hi @monikasmolarek , nothing update in the app from a design perspective, regression will be enough. It is a lib update that will help to debug issues. Update was from beta to stable release

2023-01-31 18:08 UTC, monikasmolarek commented
I can't see the User Feedback anywhere in Sentry after submitting the form. (missing: e-mail address, message body)
Please check

2023-01-31 23:39 UTC, maparr commented
Hi @monikasmolarek , fixed

2023-02-01 22:53 UTC, monikasmolarek approved these changes, later dismissed
ok now on Mac and Win10

2023-02-02 22:22 UTC, brusherru requested changes
As we discussed in person, I don't like such hacks (patching packages after installing).
Let's find a way how to avoid dirty hacks and make it works.
Could you provide steps to reproduce the bug this patch fixes?

2023-02-02 22:22 UTC, brusherru commented on app/sentry.ts
> +      }) as unknown) as Integration,
Why do we need this hack?
Seems upgrading sentry dependencies solves the issue...
`yarn upgrade -P "@sentry/*" --latest -C`

2023-02-02 22:22 UTC, brusherru commented on .github/workflows/pr-build.yml
> +      - name: yarn patch-project
I don't like this approach.
First of all, you forgot to add it to `release.yml`
Secondly, it makes project maintenance more complicated (and for such specifics obviously we need to add some documentation and keep it updated).

So, I don't like the idea of patching sentry.
However, if we really need it — I'd prefer to do it in `postinstall` or as a part of `yarn package-*`. Then we will have the same behavior everywhere. No surprises.

2023-02-02 22:22 UTC, brusherru commented on patches/@sentry+utils+7.30.0.patch
> +diff --git a/node_modules/@sentry/utils/cjs/misc.js b/node_modules/@sentry/utils/cjs/misc.js
If we need such a hack, then we really need to leave some comments here with links to opened issue in sentry repo.

2023-02-11 01:55 UTC, maparr commented on desktop/wasm_exec.js
> +				return nodeCrypto.randomFillSync(b);
I created and issue for this #1136 . 
Because of no return and replacement for the global js. I had an issue with crypto lib for node_modules

2023-02-11 03:02 UTC, maparr commented
Hi @brusherru , seems working right now. 
I created and issue for wasm. Right now not critical, but in the future need to update the lib and code. 

basically , the crypto lib func was replaced through the global var and thats why in the Sentry lib, I had an issue with the return undefined , but in the terminal everything was ok. Hope, this is it.

2023-02-14 20:47 UTC, monikasmolarek commented
@maparr the reports from Windows are not sent to Sentry (from the builds)
I tried the custom build and : 

https://user-images.githubusercontent.com/89876259/218859532-58a3bc02-b35b-42a9-bc29-c731b37ddf3c.mp4

![2023-02-14-21-43-24](https://user-images.githubusercontent.com/89876259/218859552-8191e1d2-a41f-4075-9d5f-413bd835a5bc.jpg)

2023-02-14 23:05 UTC, brusherru commented
> I tried the custom build and

I bet you didn't set up SENTRY-related env variables (DSN, AUTH_TOKEN).
But it should work for PR build...
Am I right? ;)

2023-02-14 23:07 UTC, brusherru submitted a review, later dismissed
LGTM

2023-02-14 23:11 UTC, monikasmolarek commented
I did not, you are right @brusherru , but for Mac it worked even with the GH builds, for Windows not.

2023-02-14 23:17 UTC, maparr commented
Checking on windows vm

2023-02-15 02:21 UTC, maparr commented
so yeah, I agree, wonderful behavior for Windows and different for Linux, and working for macOS. But seems to fix it by replacing lib.  Will be done in an hour.

2023-02-15 21:57 UTC, monikasmolarek approved these changes
checked quickly only on windows, looks ok!👍

2023-02-15 22:41 UTC, merged