feat(): add CANCEL button to NETWORK SETTING
spacemeshos/smapp pull request #1172
Opened 2023-02-27 14:11 UTC by maparr

2023-02-27 21:48 UTC, monikasmolarek requested changes
On MacOs looks OK
On windows :

https://user-images.githubusercontent.com/89876259/221693397-531c040d-eae1-4698-87a6-688f15a2591a.mp4

2023-02-28 02:43 UTC, maparr commented
Hi @monikasmolarek , did update , right now only for the Settings page we will be having cancel button.

2023-02-28 17:12 UTC, monikasmolarek submitted a review, later dismissed
looks ok now :)

2023-03-02 23:23 UTC, brusherru submitted a review, later dismissed

2023-03-03 04:51 UTC, merged