Password requirements to be improved
spacemeshos/smapp pull request #1198
Opened 2023-03-16 05:20 UTC by maparr

It closes #1157

2023-03-17 19:21 UTC, monikasmolarek commented
Please remember about: 
_Improve password changing option - not allowing to change the password to the exact same as the current one (which is now possible)

2023-03-17 19:25 UTC, monikasmolarek commented
Also, I would suggest showing the _YOUR 12 WORDS BACKUP_ screen right after the password step, not after the final confirmation. It's a bit confusing now.

2023-04-03 20:57 UTC, maparr commented
Hi @monikasmolarek , when u will have time, please check the new update.

2023-04-04 19:26 UTC, monikasmolarek commented
OK
Although there is one more thing I would suggest that might be improved. 
on the recording: 

- 1st input was repeatedly 123123123...
- 2nd input was 11111111111....
- 3rd input 11111111111222222222...

The feedback about the password complexity does not behave correctly. (_too short/too weak_)

https://user-images.githubusercontent.com/89876259/229894943-013e1952-9a18-4469-8735-f469e6e9f8de.mov

2023-04-10 23:18 UTC, maparr commented
> OK Although there is one more thing I would suggest that might be improved. on the recording:
> 
> * 1st input was repeatedly 123123123...
> * 2nd input was 11111111111....
> * 3rd input 11111111111222222222...
> 
> The feedback about the password complexity does not behave correctly. (_too short/too weak_)

It is an additional step that is needed as feedback.
I updated a little the titles. 
The second option is to show how long to crack the user password (weeks/days/years), I just don't think it is really needed. I can delete this message if needed.

2023-04-11 19:21 UTC, monikasmolarek submitted a review, later dismissed
👌

2023-04-17 22:31 UTC, brusherru requested changes
Left a few comments.
The rest looks good.

2023-04-17 22:31 UTC, brusherru commented on app/screens/auth/ProtectWallet.tsx
Styles should be tweaked on this screen.
In classic "Backup 12 words" it looks a bit different and does not overlap the logo.
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1897530/232622442-1cf333ed-5d31-4b23-b44d-680dd4291560.png">

2023-04-17 22:31 UTC, brusherru commented on app/screens/backup/TwelveWordsBackup.tsx
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/1897530/232622810-42243987-6d92-4343-b006-2ac15502e5d6.png">

On the classic "backup 12 words" screen button is stick to the bottom.
Tweak styles, pls

2023-04-17 22:31 UTC, brusherru commented on app/components/common/BackButton.tsx
> +  left?: number;
I don't like the idea of a generic "left" prop.
The perfect solution is to not change anything in the BackButton component and just put it in the right place (aka in the right column).

If it is not possible or will require a lot of refactoring — then ok, let's tweak BackButton but rename prop to less generic stuff.
Mb something like "isUnderLeftColumn: boolean" :)

p.s.
Also, I'm not sure that we really need `width` and `height` props as well ;)

2023-04-17 22:31 UTC, brusherru commented on app/components/settings/ChangePassword.tsx
> +    // @ts-ignore
Please, do not use `// @ts-ignore`
Most likely you need to explicitly set the proper type to `dispatch` and the problem will go away:
```
const dispatch: AppThDispatch = useDispatch();
```

2023-04-19 18:15 UTC, monikasmolarek approved these changes

2023-04-25 04:46 UTC, brusherru approved these changes
👍

2023-04-25 08:32 UTC, merged