Fix network status layers
spacemeshos/smapp pull request #1473
Opened 2023-08-25 10:42 UTC by brusherru

The problem is that Smapp started rendering "Genesis phase" because of some problem with "syncedLayer":
![image](https://github.com/spacemeshos/smapp/assets/1897530/7dd37473-7e0c-48a5-a716-bacb10cef829)

As @dshulyak proposed:

> i think there should be two things:
> clock layer: 12080  // latest according to the clock
> applied layer: 12079 // latest that was applied to vm. right now it is returned as verified. and later we will add a field that explains why it was applied (e.g hare success or tortoise weight)

So what I did:
1. Stop using `syncedLayer` and use `verifiedLayer` instead.
2. Do not render "Genesis" even if `verifiedLayer` is greater than `topLayer` for some reason. And display "genesis" only for the first two epochs.
3. If the verified layer is not more than 2 layers behind — do not scare Users and keep showing "SYNCED" status.

Preview (against the standalone network):
https://github.com/spacemeshos/smapp/assets/1897530/6a588b03-1598-4faf-990e-ad75d0a63021

2023-08-25 11:20 UTC, dshulyak commented
top layer is a layer according to the clock, have you found a condition when verified (applied) layer is higher than top layer?

2023-08-25 11:30 UTC, brusherru commented
> top layer is a layer according to the clock, have you found a condition when verified (applied) layer is higher than top layer?
Yes. It is valid for the genesis phase.
So when Smapp renders "genesis" phase — it actually swap topLayer and verifiedLayer (aka `topLayer / verifiedLayer`).
And previously this thing also renders "genesis" (as on the screenshot).
So now I'm rendering "genesis" phase only for first two epochs :)
And hopefully we won't have verifiedLayer greater than topLayer.

> i suggest to drop this. there is a boolean in the node that decides if node is synced or not synced.

Such logic will work only if the `is_synced` flag is `true`.
Otherwise, it will render "syncing layers", like `99% 11403/11404`.

I added this extra condition to avoid confusing people.
Check out this video, it demonstrates how it works without this "hack".
I believe we will have a lot of "false" reports without it :)

https://github.com/spacemeshos/smapp/assets/1897530/a58a8875-bc0d-4196-961a-428be162fa44

2023-08-25 12:55 UTC, monikasmolarek commented
How about adding the information about the current epoch on the network screen and/or a link to the Explorer? For the wallet-only mode and users without active smeshing screen there's no such info in smapp

2023-08-25 17:07 UTC, pigmej commented
I think it makes sense to simplify it.

2023-08-27 12:54 UTC, monikasmolarek commented
it actually shows now "Genesis" state while syncing with the network.

And the progress bar got spoiled

<img width="1680" alt="Screenshot 2023-08-27 at 14 52 46" src="https://github.com/spacemeshos/smapp/assets/89876259/87016557-e686-4443-9a42-5f7b459630b5">

2023-08-27 12:55 UTC, monikasmolarek requested changes
it actually shows now "Genesis" state while syncing with the network.

And the progress bar + % got spoiled
<img width="1680" alt="Screenshot 2023-08-27 at 14 52 46" src="https://github.com/spacemeshos/smapp/assets/89876259/3bec566a-d6e8-4e3c-9327-2dbf9ec60e4b">

2023-08-28 08:23 UTC, brusherru commented
> it actually shows now "Genesis" state while syncing with the network.

Yes, but actually when you're syncing from scratch on the network which passed the genesis phase.
I've fixed it, so now you'll see "SYNCING... 8063 / 12730"
And "GENESIS 555 / 8063" only when topLayer (555 in this example) is less than 8064 (tested against standalone network)

2023-08-28 10:31 UTC, merged