Fix Smapp being stuck on starting w/o internet connection
spacemeshos/smapp pull request #1559
Opened 2023-10-17 12:34 UTC by brusherru

It fixes #1546

2023-10-18 19:53 UTC, monikasmolarek requested changes
The issue persists on Windows 10 - both for autostart and manual app launching. 
[app-log.1.2.3-pr.1559.txt](https://github.com/spacemeshos/smapp/files/13033393/app-log.1.2.3-pr.1559.txt)
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/13033394/spacemesh-log-7c8cef2b.txt)

2023-10-27 18:47 UTC, maparr commented on desktop/main/startApp.ts
> +      if (!!res && !startNodeAfterUpdate) {
res is already boolean type

2023-11-01 18:32 UTC, brusherru commented
@monikasmolarek please check it out. Now it should work well.
It will try to fetch networks.json until success :)

2023-11-03 00:19 UTC, monikasmolarek commented
It works now - checked only Windows. 
But just one question: why don't we show [this modal](https://github.com/spacemeshos/smapp/blob/develop/app/screens/modal/NoInternetConnection.tsx)? The user waits for the loading screen to load and might not even notice that his Internet connection is off.

2023-11-03 06:04 UTC, brusherru commented
@monikasmolarek 

> But just one question: why don't we show [this modal](https://github.com/spacemeshos/smapp/blob/develop/app/screens/modal/NoInternetConnection.tsx)?

We're showing (at least it works on MacOS) 🤔
And, actually, it is displayed before you can unlock the wallet.
So this PR makes most sense for the case when auto-start is turned on, because Smapp starts Node before the User unlocks the wallet.

However, this modal is shown only when you have no connection at all (e.g. wi-fi turned off, no ethernet cable, etc).
In case you have Wi-Fi turned on, but for some reason the internet is not working (firewall / DNS issue / router still establishing connection / etc) — it would not be shown.

--
If everything is good — please click on "Review" button and choose "Approve" option ;)

2023-11-03 07:26 UTC, maparr approved these changes

2023-11-03 10:50 UTC, monikasmolarek commented
https://github.com/spacemeshos/smapp/assets/89876259/0dcc7fe2-ca28-4c82-afb4-571bca743b98

It seems this modal just does not at all, not only within this PR. I will check more carefully and open a separate issue for it.

2023-11-03 11:28 UTC, maparr commented
Hi @monikasmolarek, it seems that Windows is not displaying the issue correctly. macOS, whether it's within a PR or release, works well. I cannot verify this properly as I am using Parallels, and there might be an issue with the navigator restrictions or Parallels itself. I don't see a reason for this issue. I cannot properly check on a cloud VM because it relies on an internet connection. I will try to find a PC and check this in the evening.

To be sure, at least for macOS, many scenarios are working well. This includes scenarios where there is no internet connection at the start of the app or when it gets disconnected during app use, whether it's on the login screen or internal pages.

However, I am pretty sure there is some issue on Windows. That's why the message wasn't seen on Windows, and they might not have been aware of the internet problems.

2023-11-03 17:59 UTC, maparr commented
@monikasmolarek, maybe I understand how you've faced this issue. You can click the 'ignore' button in this modal, and it should work as expected. Ignoring it will fully disable the modal for all other scenarios, in case the user doesn't want to see it or if there are issues with unstable internet, etc.

2023-11-03 20:12 UTC, monikasmolarek commented
@maparr wait wait, do you mean, that one click on the "Ignore" button dismisses this modal forever? 
We should have separate "don’t show ever again" and "ignore this time" buttons. Or if it's too much for this app version, then at least a phrase of explanation... 
Anyway, that was not the case. It was a fresh app, all clear, I have never seen this modal, and never clicked "Ignore". 

And there are other issues with it, also on macOS, so I am creating a report anyway.

2023-11-03 20:16 UTC, monikasmolarek approved these changes

2023-11-06 12:40 UTC, merged