Fix/1477
spacemeshos/smapp pull request #1572
Opened 2023-11-01 18:56 UTC by maparr

it closes #1477

2023-11-02 08:03 UTC, brusherru requested changes
You have overcomplicated everything, while didn't make it robust at all :-\

2023-11-02 08:03 UTC, brusherru commented on app/components/auth/DragAndDrop.tsx
How to reproduce the mentioned "undefined if no files" issue?
As I know, it will be an empty string by default.
So, if I'm wrong — describe a way to reproduce and change Props type to a proper one.

2023-11-02 08:03 UTC, brusherru commented on app/redux/wallet/actions.ts
>      await eventsService.addWalletPath(filePath);
Why not just validate the wallet file within `addWalletPath` handler?
Then there will be no changes required at all.

2023-11-02 08:03 UTC, brusherru commented on desktop/main/walletFile.ts
> +
Absolutely wrong validity check.
It sounds like a guard, but actually it does an I/O and does not check format except that it is JSON.
Remove it.

2023-11-02 09:13 UTC, maparr commented on app/components/auth/DragAndDrop.tsx
Uploading Screen Recording 2023-11-02 at 09.12.08.mov…

2023-11-02 14:41 UTC, brusherru commented on app/components/auth/DragAndDrop.tsx
Okay, got it.
It is actually about `files?.length` and not related to `fileName` (so `Props` is valid).

2023-11-02 14:55 UTC, maparr commented on app/components/auth/DragAndDrop.tsx
yes

2023-11-02 15:13 UTC, brusherru requested changes

2023-11-02 15:13 UTC, brusherru commented on app/redux/wallet/actions.ts
> +    dispatch(setUiError(new Error(errorMessage)));
No need to add a specific handler here and overcomplicate return type of `addWalletPath`

2023-11-02 15:13 UTC, brusherru commented on desktop/main/Wallet.ts
> +
Please use consistent types. Since it returns `string[]` — it should not return `false` for "invalidity" case. But it should throw an Error instead (and it is already handled "for free").

2023-11-02 15:13 UTC, brusherru commented on desktop/main/walletFile.ts
> +      typeof crypto.cipherText === 'string';
Move this into `shared/types/guards.ts` module and name function `isWalletMeta`.

2023-11-02 15:13 UTC, brusherru commented on desktop/main/walletFile.ts
> +        typeof salt === 'string'
You can add it to `isWalletGCMEncrypted` guard.

2023-11-02 15:13 UTC, brusherru commented on desktop/main/walletFile.ts
> +export const isWalletFileValid = async (filePath: string) => {
This entire function should not persist in such a form.
Instead, please implement `isWalletMeta` and `isWalletFile` guards within `shared/types/guards.ts` module. And use it.

Pay attention, that they should not do any I/O or side effects.

2023-11-02 15:13 UTC, brusherru commented on desktop/main/walletFile.ts
> +  return JSON.parse(fileContent);
After implementing guards, do:
```suggestion
  const content = JSON.parse(fileContent);
  if (!isWalletFile(content)) {
    throw new Error(`File ${path} is not a valid wallet file`);
  }
  return content;
```

No more changes are needed.

2023-11-02 15:13 UTC, brusherru commented on tests/walletFiles.spec.ts
You can keep tests (but move them in a separate module: `guards.spec.ts`) for newly created guards and re-use these fixtures.

2023-11-02 22:29 UTC, monikasmolarek commented
@maparr please let me know once every suggestion resolved and I could start testing on all 3 OSes

2023-11-06 10:31 UTC, brusherru requested changes

2023-11-06 10:31 UTC, brusherru commented on desktop/main/Wallet.ts
> +    }
1. Do not repeat yourself. If you want to have more user-friendly error message about invalid JSON — catch & rethrow the error inside `loadRawWallet` instead.
2. We already have type for `{ error, result }` and helper function...
3. `Error` type is serializing automatically into `{ message, stack }` when sent via IPC.

```suggestion
      try {
        await loadRawWallet(filePath);
        const oldWalletFiles = StoreService.get('walletFiles');
        const newWalletFiles = R.uniq([...oldWalletFiles, filePath]);
        StoreService.set('walletFiles', newWalletFiles);
        return createIpcResponse(null, newWalletFiles);
      } catch (err: any) {
        return createIpcResponse(err, null);
      }
    }
```

2023-11-06 10:31 UTC, brusherru commented on desktop/main/Wallet.ts
> +    }> => {
No need to reinvent such types...
```suggestion
    ): Promise<IpcResponse<string[]>> => {
```

2023-11-06 10:31 UTC, brusherru commented on shared/types/guards.ts
> +  Boolean(a && a.meta && a.crypto);
It is not enough to ensure the type. Wrong guard.
```suggestion
```

2023-11-06 10:31 UTC, brusherru commented on shared/types/guards.ts
> +};
1. All guards are pure functions with object property checks. No need to wrap it into try-catch, if there is some exception has occurred — it means that there is a bug in the code.
2. It is not a TS guard.

```suggestion
export const isWalletFile = (wallet: any): wallet is WalletFile => (
   wallet &&
   isWalletMeta(wallet.meta) &&
   isWalletSecretsEncrypted(wallet.crypto) &&
   (
     isWalletGCMEncrypted(wallet.crypto) ||
     isWalletLegacyEncrypted(wallet.crypto)
   );
```

2023-11-06 10:31 UTC, brusherru commented on tests/fixtures/my_wallet_gcm.json
What's changed? What is the purpose?

2023-11-06 10:31 UTC, brusherru commented on tests/shared/types/guards.spec.ts
👍

2023-11-06 10:31 UTC, brusherru commented on tests/walletFiles.spec.ts
👍

2023-11-06 10:31 UTC, brusherru commented on app/infra/eventsService/eventsService.ts
> +  }> => ipcRenderer.invoke(ipcConsts.W_M_ADD_WALLET_PATH, filePath);
```suggestion
  ): Promise<IpcResponse<string[]>> => ipcRenderer.invoke(ipcConsts.W_M_ADD_WALLET_PATH, filePath);
```

2023-11-06 10:31 UTC, brusherru commented on app/redux/wallet/actions.ts
> +      new Error(error)
```suggestion
      new Error(error.message)
```

2023-11-06 10:41 UTC, maparr commented on tests/fixtures/my_wallet_gcm.json
I checked, the spaces only. Autosave. I can revert this file.

2023-11-07 01:08 UTC, maparr commented
@monikasmolarek u can take a look.

2023-11-08 00:34 UTC, monikasmolarek approved these changes
all good from the user perspective. There's just one corner case: 
1. try to load an incorrect wallet
1. get the error msg
1. fix the file
1. try to load it again
-in this case it is not checked/assessed, the path is remembered as incorrect, only ulnikning this path and selecting again will let us choose the same file. 
But I don’t think it it's any crucial or important to cover, especially for this smapp version

2023-11-08 14:41 UTC, brusherru approved these changes
LGTM

2023-11-08 15:14 UTC, merged