Upload artifacts to CFS
spacemeshos/smapp pull request #1622
Opened 2023-12-22 21:00 UTC by andres-spacemesh

The release of the github action was configured so that the artifacts are uploaded to the R2 bucket of Cloudflare Storage.

2023-12-25 16:58 UTC, brusherru commented on .github/workflows/releaseGC.yml
Wouldn't it conflict with another workflow? 🤔 
1. There might be only one release per tag
2. They are both uploading to the same R2 bucket

So what is the purpose of having two workflows?

2023-12-26 06:14 UTC, andres-spacemesh commented on .github/workflows/releaseGC.yml
I wanna to keep the GCS bucket in the meantime to avoid any conflict with the current release process.
For now, lets just add the step to upload to R2 smapp bucket

2023-12-27 14:29 UTC, brusherru requested changes
It is failing: https://github.com/spacemeshos/smapp/actions/runs/7327798914/job/19963214983#step:14:34

2024-01-02 16:14 UTC, brusherru approved these changes
OK. Now it is working as expected.

2024-01-02 16:15 UTC, merged