Rename *SMD symbol to Smidge and add a better input for amounts
spacemeshos/smapp pull request #805
Opened 2021-08-26 01:16 UTC by brusherru

It closes #738

The new amount input:
![It looks like this](https://user-images.githubusercontent.com/1897530/130623456-264a2911-5711-4ce9-9f81-9dc28b6dac47.gif)

And I think that we can use this until we have a better design for the input ;)

It does not include handling amounts with precision (using `BigInt`), and that's why:

1. It requires touching a lot of code and regenerate some JS files generated from proto files. I think it's better to do such a big thing within the separate PR, especially since it requires careful testing of everything.
2. Also, it seems (https://github.com/spacemeshos/go-spacemesh/issues/2718#issuecomment-905974522) that Node will have some fixes related to data types of the balance. As a consequence, the proto interface will change to something else, which can store such a big amount. So I'm sure that we should return to this issue when we will have a new interface to avoid doing the same job twice.

Anyway, I have saved all my developments in a separate branch, so we can return back to them in the future.

---

Also, I have a small separate commit, that constrains the maximum input to `Number.MAX_SAFE_INTEGER` (9007199254740991) or even to the balance (when you want to send something).
But I think that doesn't look nice: you typing some amount and then... BANG! there is another amount in the input. Or if you have 0 SMH on the balance it will always be zero regardless of what you type in.
It is confusing. If you want to see it in action, tell me — I'll push a commit / separate branch ;)

2021-08-26 04:19 UTC, avive commented
lgtm

2021-08-26 05:40 UTC, avive submitted a review, later dismissed
LGTM

2021-08-26 05:45 UTC, avive requested changes
Small comments - can we please get rid of the green color of the units when the button is clicked? I'm not sure it adds anything. When we need is well-specified hover-color and clicked-color to make this button feel like it is part of the ui kit/theme @vomcent

2021-08-26 07:43 UTC, brusherru commented
I highlight units with the green color on hover, on click focus moved to the input, so it won't be green anymore if User moved away the cursor.
Do you mean that I should highlight it with the background color instead of text color as other buttons do?

2021-08-26 07:59 UTC, brusherru commented
Something like this?
![button-demo](https://user-images.githubusercontent.com/1897530/130924579-844b62b1-d54d-4b13-9c72-4cbfb23dcaed.gif)

2021-08-26 08:45 UTC, avive commented
for sure not replacing the color on click - let's get exact color recommendations from vincent but generally yes - hover color and mousedown color like we have for most other buttons.

2021-08-27 09:36 UTC, avive approved these changes

2021-08-27 09:36 UTC, merged